---
title: "CVICU Patient Dashboard"
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
    }
</style>

```{r setup, include=FALSE}

# knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = 'U:', output_file = 'dashboard_cvicu.html') })

# mount_smbfs //brgulbis@tmcisilon/user$/user1/brgulbis /Users/briangulbis/Share/U
# mount_smbfs //brgulbis@mh.org/public /Users/briangulbis/Share/W

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readxl)
library(lubridate)
library(DT)
library(sparkline)

spark_lines <- function(x, y, nl_min, nl_max, type = "line") {
    spk_chr(
        values = y,
        type = type,
        xvalues = x,
        width = 50,
        lineColor = "black",
        fillColor = FALSE,
        highlightLineColor = "orange",
        highlightSpotColor = "blue",
        normalRangeMin = nl_min[1],
        normalRangeMax = nl_max[1]
    )
}

ref_normals <- tibble(
    event = c(
        "scr",
        "wbc",
        "hgb",
        "platelet",
        "glucose",
        "hr",
        "sbp",
        "uop",
        "temperature",
        "inr"
    ),
    normal_min = c(0.5, 3.7, 8.5, 133, 80, 60, 90, 50, 97.5, 1.5),
    normal_max = c(1.4, 10.4, 10, 250, 180, 100, 140, 150, 100.5, 3)
)

```

```{r read_data}
# file_nm <- "U:/Data/patient_dashboard/dashboard_data_daily.xlsx"
# file_nm <- "../data/raw/dashboard_data_daily.xlsx"
# file_nm <- "/Users/briangulbis/Share/U/Data/patient_dashboard/dashboard_data_daily.xlsx"
file_nm <- "/Volumes/brgulbis/Data/patient_dashboard/dashboard_data_daily.xlsx"

if (as_date(file.info(file_nm)$mtime) < today()) {
    warning("Data from previous day")
}

data_dash <- read_excel(file_nm, sheet="dashboard") %>%
    rename_all(tolower) %>%
    mutate_at("bands", list(~ . / 100))

data_events <- read_excel(file_nm, sheet="events") %>%
    rename_all(tolower)

data_drips <- read_excel(file_nm, sheet="drips") %>%
    rename_all(tolower)

```

```{r sparklines}
sparks <- data_events %>%
    mutate(
        hrs = difftime(
            event_datetime,
            now(),
            units = "hours"
        )
    ) %>%
    left_join(ref_normals, by = "event") %>%
    add_count(encntr_id, event) %>%
    filter(n > 1) %>%
    group_by(encntr_id, event) %>%
    summarize_at(
        "result_val", 
        list(
            ~spark_lines(
                x = hrs, 
                y = ., 
                nl_min = normal_min,
                nl_max = normal_max
            )
        )
    ) %>%
    # pivot_wider(
    #     names_from = event,
    #     values_from = result_val,
    #     names_prefix = "spark_"
    # )
    spread(event, result_val)
```

```{r baseline_values}
base_vals <- data_events %>%
    filter(
        event %in% c(
            "hgba1c",
            "chol",
            "trig",
            "hdl",
            "ldl",
            "tsh"
        )
    ) %>%
    arrange(encntr_id, event, desc(event_datetime), desc(event_id)) %>%
    distinct(encntr_id, event, .keep_all = TRUE) %>%
    select(encntr_id, event, result_val) %>%
    pivot_wider(
        names_from = event, 
        values_from = result_val,
        names_prefix = "base_"
    )
```

```{r current_values}
curr_vals <- data_events %>%
    filter(
        event %in% c(
            "temperature",
            "scr",
            "wbc",
            # "bands",
            "hgb",
            "platelet",
            "inr",
            "sodium",
            "potassium",
            "ptt",
            "alt",
            "ast",
            "tbili"
        )
    ) %>%
    arrange(encntr_id, event, desc(event_datetime), desc(event_id)) %>%
    distinct(encntr_id, event, .keep_all = TRUE) %>%
    select(encntr_id, event, result_val) %>%
    pivot_wider(
        names_from = event, 
        values_from = result_val,
        names_prefix = "curr_"
    )
```

```{r max_values}
max_vals <- data_events %>%
    filter(event == "temperature") %>%
    group_by(encntr_id, event) %>%
    summarize_at("result_val", max, na.rm = TRUE) %>%
    pivot_wider(
        names_from = event, 
        values_from = result_val,
        names_prefix = "max_"
    )
```

```{r sum_values}
sum_vals <- data_events %>%
    filter(event == "uop") %>%
    group_by(encntr_id, event) %>%
    summarize_at("result_val", sum, na.rm = TRUE) %>%
    pivot_wider(
        names_from = event, 
        values_from = result_val,
        names_prefix = "sum_"
    )
```

```{r drips}
drips <- data_drips %>%
    mutate(drip = paste(str_extract(medication, "^.{3}"), rate)) %>%
    group_by(encntr_id) %>%
    summarize_at("drip", str_c, collapse = ", ")

```


```{r datatable}
col_names <- c(
    "Room",
    "Patient", 
    "Age",
    "Sex",
    "Wt",
    "LOS",
    "SOFA",
    "Temp Trend",
    "Tmax",
    "SCr Trend",
    "SCr",
    "CrCl",
    "Dialysis",
    "WBC Trend", 
    "WBC",
    "Bands",
    "Hgb Trend",
    "Hgb",
    "Plt Trend",
    "Plt",
    "SBP Trend",
    "HR Trend", 
    "Drips",
    "Devices",
    "Gluc Trend",
    "SSI",
    "INR Trend",
    "INR",
    "PTT",
    "UOP Trend",
    "UOP",
    "Avg",
    "Net",
    "Sod",
    "Pot",
    "T.Bili",
    "AST",
    "ALT",
    "A1c",
    "TSH",
    "Chol",
    "Trig",
    "HDL",
    "LDL",
    "PCA",
    "Demands",
    "MRSA",
    "COVID-19"
)

df <- data_dash %>% 
    left_join(sparks, by = "encntr_id") %>%
    left_join(base_vals, by = "encntr_id") %>%
    left_join(curr_vals, by = "encntr_id") %>%
    left_join(max_vals, by = "encntr_id") %>%
    left_join(sum_vals, by = "encntr_id") %>%
    left_join(drips, by = "encntr_id") %>%
    select(
        nurse_unit,
        bed,
        name,
        age,
        sex,
        weight,
        los,
        sofa,
        temperature,
        max_temperature,
        scr,
        curr_scr,
        crcl,
        dialysis,
        wbc,
        curr_wbc,
        bands,
        hgb,
        curr_hgb,
        platelet,
        curr_platelet,
        sbp,
        hr,
        drip,
        iabp,
        glucose,
        ssi,
        inr,
        curr_inr,
        curr_ptt,
        uop,
        sum_uop,
        uop_avg,
        net_io,
        curr_sodium,
        curr_potassium,
        curr_tbili,
        curr_ast,
        curr_alt,
        base_hgba1c,
        base_tsh,
        base_chol,
        base_trig,
        base_hdl,
        base_ldl,
        pca_doses,
        pca_demands,
        mrsa_pcr,
        covid_19
    )

make_table <- function(x) {
    x %>%
        select(-nurse_unit) %>%
        datatable(
            # caption = paste0(
            #     "Data updated: ", 
            #     format(file.info(file_nm)$mtime, "%B %d, %Y at %I:%M %p")
            # ),
            caption = htmltools::tags$caption(
                style = "caption-side: bottom",
                paste0(
                    "Data updated: ", 
                    format(file.info(file_nm)$mtime, "%B %d, %Y at %I:%M %p")
                )
            ),
            # height = 800,
            rownames = FALSE, 
            escape = FALSE,
            colnames = col_names,
            # extensions = "FixedHeader",
            extensions = c("FixedColumns", "FixedHeader"),
            # fillContainer = TRUE,
            options = list(
                dom = "t",
                # fixedColumns = TRUE,
                fixedColumns = list(leftColumns = 2),
                fixedHeader = TRUE,
                # scrollX = "300px",
                # scrollX = TRUE,
                # scrollY = TRUE,
                pageLength = 21,
                order = list(list(0, 'asc')),
                initComplete = JS(
                    "function(settings, json) {",
                    "$(this.api().table().header()).css({'font-size': '80%'});",
                    "}"
                ),
                fnDrawCallback = JS(
                    "function(){ HTMLWidgets.staticRender(); }"
                )
            )
        ) %>%
        formatRound(c("base_tsh", "curr_inr", "curr_scr"), 2) %>%
        formatRound(c("los", "max_temperature", "uop_avg", "base_hgba1c", "curr_potassium", "curr_wbc", "curr_hgb"), 1) %>%
        formatRound(c("crcl", "sum_uop", "net_io", "curr_ptt", "weight", "curr_ast", "curr_alt"), 0) %>%
        formatPercentage("bands", 0) %>%
        formatStyle("crcl", fontWeight = styleInterval(29, c("bold", "normal"))) %>%
        formatStyle("curr_sodium", fontWeight = styleInterval(c(131, 149), c("bold", "normal", "bold"))) %>%
        formatStyle("curr_potassium", fontWeight = styleInterval(c(3.5, 5.5), c("bold", "normal", "bold"))) %>%
        formatStyle("curr_tbili", fontWeight = styleInterval(2, c("normal", "bold"))) %>%
        formatStyle(c("curr_ast", "curr_alt"), fontWeight = styleInterval(75, c("normal", "bold"))) %>%
        formatStyle("base_hgba1c", fontWeight = styleInterval(8, c("normal", "bold"))) %>%
        formatStyle("base_tsh", fontWeight = styleInterval(c(0.4, 3.75), c("bold", "normal", "bold"))) %>%
        formatStyle(columns = c(1:ncol(df)), fontSize = "80%") %>%
        spk_add_deps()
}

```

```{r}
df %>%
    filter(nurse_unit == "HH CVICU") %>%
    make_table()

message(paste("Data updated:", format(file.info(file_nm)$mtime, "%B %d, %Y at %I:%M %p")))

```
