---
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

<style>
    body .main-container {
        max-width: 100%;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(stringr)
library(DT)
library(sparkline)

update_time <- list.files("../data/raw") %>%
    str_replace_all("cvicu_dashboard_|\\.xlsx", "") %>%
    ymd_hms()
raw <- list.files("../data/raw", full.names = TRUE) 
data_patients <- read_excel(raw, sheet = "Patients", skip = 2, col_names = c("millennium.id", "name", "age", "gender", "los")) 
data_labs <- read_excel(raw, sheet = "Labs", skip = 2, col_names = c("millennium.id", "lab.datetime", "lab", "lab.result"))
data_meds <- read_excel(raw, sheet = "Meds", skip = 2, col_names = c("millennium.id", "med.datetime", "med", "dose", "dose.units", "route", "rate", "rate.units", "infuse.actions"))
data_vitals <- read_excel(raw, sheet = "Vitals", skip = 2, col_names = c("millennium.id", "vital.datetime", "vital", "vital.result", "vital.units"))
data_temps <- read_excel(raw, sheet = "Temps", skip = 2, col_names = c("millennium.id", "vital.datetime", "vital", "vital.result", "vital.units"))
data_uop <- read_excel(raw, sheet = "UOP", skip = 2, col_names = c("millennium.id", "uop.datetime", "uop", "uop.result", "uop.units"))
data_measures <- read_excel(raw, sheet = "Measures", skip = 2, col_names = c("millennium.id", "measure.datetime", "measure", "measure.result", "measure.units"))
```

```{r}
df_spark <- data_labs %>%
    filter(floor_date(lab.datetime, unit = "day") >= ymd(today()) - days(3),
           lab %in% c("Creatinine Lvl", "Hgb", "Platelet", "WBC")) %>%
    mutate(lab.drawn = difftime(lab.datetime, now(), units = "hours")) %>%
    group_by(millennium.id, lab) %>%
    arrange(lab.datetime, .by_group = TRUE) %>%
    unite(x_y, lab.drawn, lab.result, sep = ":") %>%
    summarize_at("x_y", funs(paste(., collapse = ","))) %>%
    spread(lab, x_y) 

df_measures <- data_measures %>%
    mutate_at("measure.result", as.numeric) %>%
    mutate_at("measure", str_to_lower) %>%
    filter((measure == "weight" & measure.units == "kg") | 
               (measure == "height" & measure.units == "cm"),
           !is.na(measure.result)) %>%
    arrange(millennium.id, measure, desc(measure.datetime)) %>%
    distinct(millennium.id, measure, .keep_all = TRUE) %>%
    select(millennium.id, measure, measure.result) %>%
    spread(measure, measure.result)

hd <- c("Hemodialysis Output Volume", "Hemodialysis Output Vol")
crrt <- c("CRRT Output Vol", "CRRT Actual Pt Fluid Removed Vol")
pd <- c("Peritoneal Dialysis Output Vol", "Peritoneal Dialysis Output Volume")

df_uop <- data_uop %>%
    mutate_at("uop.result", as.numeric) %>%
    filter(floor_date(uop.datetime, unit = "day")  >= ymd(today()) - days(2),
           !(uop %in% c(hd, crrt, pd))) %>%
    mutate(uop_hr = floor_date(uop.datetime, unit = "hour"),
           uop_date = if_else(hour(uop_hr) <= 7, floor_date(uop_hr - days(1), unit = "day"), floor_date(uop_hr, unit = "day"))) %>%
    group_by(millennium.id, uop_date) %>%
    summarize_at("uop.result", sum, na.rm = TRUE) %>%
    left_join(df_measures, by = "millennium.id") %>%
    mutate(uop_rate = uop.result / weight / 24) %>%
    filter(uop_date == today() - days(1)) %>%
    select(millennium.id, uop_rate)

dialysis <- c("Hemodialysis Output Volume" = "HD", 
              "Hemodialysis Output Vol" = "HD",
              "CRRT Output Vol" = "CRRT",
              "CRRT Actual Pt Fluid Removed Vol" = "CRRT",
              "Peritoneal Dialysis Output Vol" = "PD",
              "Peritoneal Dialysis Output Volume" = "PD")

df_dialysis <- data_uop %>%
    filter(floor_date(uop.datetime, unit = "day")  >= ymd(today()) - days(2),
           (uop %in% c(hd, crrt, pd))) %>%
    mutate_at("uop", str_replace_all, pattern = dialysis) %>%
    distinct(millennium.id, uop) %>%
    rename(alert = uop)

df_alert <- data_labs %>%
    filter(floor_date(lab.datetime, unit = "day") >= ymd(today()) - days(2),
           lab %in% c("AST", "ALT", "Lactic Acid Lvl", "POC A LA")) %>%
    mutate_at("lab.result", as.numeric) %>%
    mutate_at("lab", str_replace_all, pattern = "Lactic Acid Lvl|POC A LA", replacement = "LA") %>%
    group_by(millennium.id, lab) %>%
    summarize_at("lab.result", max, na.rm = TRUE) %>%
    filter((lab == "AST" & lab.result >= 300) |
               (lab == "ALT" & lab.result >= 300) |
               (lab == "LA" & lab.result >= 4)) %>%
    rename(alert = lab) %>%
    bind_rows(df_dialysis) %>%
    group_by(millennium.id) %>%
    summarize_at("alert", str_c, collapse = ",")

vital_names <- c("Arterial Systolic BP 1" = "SBP",
                 "Systolic Blood Pressure" = "SBP",
                 "Respiratory Rate" = "RR",
                 "Glasgow Coma Score" = "GCS",
                 "Apical Heart Rate" = "HR",
                 "POC A PO2" = "PO2",
                 "POC A %FIO2" = "FIO2",
                 "FIO2 \\(%\\)" = "FIO2",
                 "Mean Arterial Pressure (Invasive)" = "MAP",
                 "Mean Arterial Pressure" = "MAP")

df_vitals <- data_vitals %>%
    filter(floor_date(vital.datetime, unit = "day") >= ymd(today()) - days(1)) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    filter(vital %in% c("SBP", "HR")) %>%
    select(-vital.units) %>%
    mutate(vital.drawn = difftime(vital.datetime, now(), units = "hours")) %>%
    group_by(millennium.id, vital) %>%
    arrange(vital.datetime, .by_group = TRUE) %>%
    unite(x_y, vital.drawn, vital.result, sep = ":") %>%
    summarize_at("x_y", funs(paste(., collapse = ","))) %>%
    spread(vital, x_y) %>%
    select(millennium.id, SBP, HR)

sofa_vitals <- data_vitals %>%
    filter(floor_date(vital.datetime, unit = "day") >= ymd(today()) - hours(24)) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    filter(vital %in% c("MAP", "GCS")) %>%
    group_by(millennium.id, vital) %>%
    summarize_at("vital.result", "min", na.rm = TRUE) %>%
    spread(vital, vital.result) %>%
    mutate_at("GCS", funs(case_when(. < 6 ~ 4,
                                    . <= 9 ~ 3,
                                    . <= 12 ~ 2,
                                    . <= 14 ~ 1,
                                    TRUE ~ 0))) %>%
    mutate_at("MAP", funs(case_when(. < 70 ~ 1,
                                    TRUE ~ 0)))

sofa_vent <- data_measures %>%
    filter(floor_date(measure.datetime, unit = "day") >= ymd(today()) - hours(24),
           measure == "Invasive Ventilation Mode") %>%
    distinct(millennium.id) %>%
    mutate(vent = TRUE)

sofa_resp <- data_vitals %>%
    filter(floor_date(vital.datetime, unit = "day") >= ymd(today()) - hours(24)) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    filter(vital %in% c("PO2", "FIO2")) %>%
    select(-vital.units) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    summarize_at("vital.result", funs(vital_min = min, vital_max = max)) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    mutate(vital.result = if_else(vital == "PO2", vital_min, vital_max)) %>%
    select(-vital_min, -vital_max) %>%
    spread(vital, vital.result) %>%
    group_by(millennium.id) %>%
    arrange(vital.datetime, .by_group = TRUE) %>%
    fill(FIO2) %>%
    mutate(ratio = PO2 / (FIO2 / 100)) %>%
    filter(!is.na(ratio)) %>%
    summarize_at("ratio", "min", na.rm = TRUE) %>%
    left_join(sofa_vent, by = "millennium.id") %>%
    mutate(resp_score = case_when(ratio < 100 & vent ~ 4,
                             ratio < 200 & vent ~ 3,
                             ratio < 300 ~ 2,
                             ratio < 400 ~ 1,
                             TRUE ~ 0)) %>%
    select(millennium.id, resp_score)

labs <- c("Creatinine Lvl" = "scr",
          "Platelet" = "plt", 
          "Bili Total" = "bili")

sofa_labs <- data_labs %>%
    filter(floor_date(lab.datetime, unit = "day") >= ymd(today()) - hours(24),
           lab %in% c("Creatinine Lvl", "Platelet", "Bili Total")) %>%
    mutate_at("lab", str_replace_all, pattern = labs) %>%
    mutate_at("lab.result", as.numeric) %>%
    arrange(millennium.id, lab, lab.datetime) %>%
    distinct(millennium.id, lab, lab.datetime, .keep_all = TRUE) %>%
    group_by(millennium.id, lab.datetime) %>%
    spread(lab, lab.result) %>%
    group_by(millennium.id) %>%
    summarize_at(c("scr", "plt", "bili"), funs(min, max), na.rm = TRUE) %>%
    select(millennium.id, scr_max, plt_min, bili_max) %>%
    mutate_at("scr_max", funs(case_when(. >= 5 ~ 4,
                                        . >= 3.5 ~ 3,
                                        . >= 2 ~ 2,
                                        . >= 1.2 ~ 1,
                                        TRUE ~ 0))) %>%
    mutate_at("plt_min", funs(case_when(. < 20 ~ 4,
                                        . < 50 ~ 3,
                                        . < 100 ~ 2,
                                        . < 150 ~ 1,
                                        TRUE ~ 0))) %>%
    mutate_at("bili_max", funs(case_when(. >= 12 ~ 4,
                                         . >= 6 ~ 3,
                                         . >= 2 ~ 2,
                                         . >= 1.2 ~ 1,
                                         TRUE ~ 0)))
    
sofa_uop <- data_uop %>%
    mutate_at("uop.result", as.numeric) %>%
    filter(floor_date(uop.datetime, unit = "day")  >= ymd(today()) - days(2),
           !(uop %in% c(hd, crrt, pd))) %>%
    mutate(uop_hr = floor_date(uop.datetime, unit = "hour"),
           uop_date = if_else(hour(uop_hr) <= 7, 
                              floor_date(uop_hr - days(1), unit = "day"), 
                              floor_date(uop_hr, unit = "day"))) %>%
    group_by(millennium.id, uop_date) %>%
    summarize_at("uop.result", sum, na.rm = TRUE) %>%
    filter(uop_date == ymd(today() - days(1))) %>%
    mutate_at("uop.result", funs(case_when(. < 200 ~ 4,
                                           . < 500 ~ 3,
                                           TRUE ~ 0))) %>%
    select(millennium.id, uop.result)

sofa_meds <- data_meds %>%
    mutate_at("med", str_to_lower) %>%
    filter(floor_date(med.datetime, unit = "day") >= ymd(today()) - hours(24),
           med %in% c("dopamine", "dobutamine", "epinephrine", "norepinephrine"),
           !is.na(rate.units),
           rate > 0) %>%
    left_join(df_measures, by = "millennium.id") %>%
    mutate(rate_kg = if_else(rate.units == "microgram/min", rate / weight, rate)) %>%
    group_by(millennium.id, med) %>%
    summarize_at("rate_kg", funs(rate_max = max), na.rm = TRUE) %>%
    mutate_at("med", factor, levels = c("dopamine", "dobutamine", "epinephrine", "norepinephrine")) %>%
    spread(med, rate_max, drop = FALSE, fill = 0) %>%
    mutate_at("dopamine", funs(case_when(. > 15 ~ 4,
                                         . > 5 ~ 3,
                                         . > 0 ~ 2,
                                         TRUE ~ 0))) %>%
    mutate_at("dobutamine", funs(case_when(. > 0 ~ 2,
                                           TRUE ~ 0))) %>%
    mutate_at(c("epinephrine", "norepinephrine"), funs(case_when(. > 0.1 ~ 4,
                                                                 . > 0 ~ 3,
                                                                 TRUE ~ 0)))

df_sofa <- data_patients %>%
    select(millennium.id) %>%
    left_join(sofa_resp, by = "millennium.id") %>%
    left_join(sofa_labs, by = "millennium.id") %>%
    left_join(sofa_vitals, by = "millennium.id") %>%
    left_join(sofa_uop, by = "millennium.id") %>%
    left_join(sofa_meds, by = "millennium.id") %>%
    mutate_all(funs(coalesce(., 0))) %>%
    group_by(millennium.id) %>%
    mutate(bp_score = max(MAP, dopamine, dobutamine, epinephrine, norepinephrine, na.rm = TRUE),
           renal_score = max(scr_max, uop.result, na.rm = TRUE),
           sofa = resp_score + plt_min + GCS + bili_max + bp_score + renal_score) %>%
    select(millennium.id, sofa)

df_qsofa <- data_vitals %>%
    filter(floor_date(vital.datetime, unit = "day") >= ymd(today()) - days(1)) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    select(-vital.units) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    summarize_at("vital.result", min) %>%
    spread(vital, vital.result) %>%
    select(-HR) %>%
    group_by(millennium.id) %>%
    fill(GCS) %>%
    group_by(millennium.id) %>%
    summarize_at(c("SBP", "RR", "GCS"), c("min", "max"), na.rm = TRUE) %>%
    group_by(millennium.id) %>%
    mutate(qsofa = sum(SBP_min <= 100, RR_max >= 22, GCS_min < 15, na.rm = TRUE)) %>%
    select(millennium.id, qsofa)
    
df_temps <- data_temps %>%
    filter(vital.datetime >= now() - hours(24),
           vital.units == "DegF") %>%
    mutate_at("vital.result", as.numeric) %>%
    group_by(millennium.id) %>%
    summarize_at("vital.result", max)

df <- data_patients %>%
    mutate_at("gender", str_extract, pattern = "^M|^F") %>%
    left_join(df_sofa, by = "millennium.id") %>%
    # left_join(df_qsofa, by = "millennium.id") %>%
    left_join(df_temps, by = "millennium.id") %>%
    left_join(df_spark, by = "millennium.id") %>%
    left_join(df_vitals, by = "millennium.id") %>%
    left_join(df_uop, by = "millennium.id") %>%
    left_join(df_alert, by = "millennium.id") %>%
    select(-millennium.id)

i <- 5

colDefs1 <- list(
    list(targets = seq(1, i, 1), width = '20px'),
    list(targets = i + 1, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_scr>' + data + '</span>' }")),
    list(targets = i + 2, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_hgb>' + data + '</span>' }")),
    list(targets = i + 3, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_plt>' + data + '</span>' }")),
    list(targets = i + 4, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_wbc>' + data + '</span>' }")),
    list(targets = i + 5, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_sbp>' + data + '</span>' }")),
    list(targets = i + 6, width = '60px', render = JS("function(data, type, full){ return '<span class=spark_hr>' + data + '</span>' }")),
    list(targest = i + 7, width = '15px'),
    list(targest = i + 8, width = '30px')
)

line_string <- "type: 'line', width: '50px', lineColor: 'black', fillColor: false, highlightLineColor: 'orange', highlightSpotColor: 'orange'"

normal_scr <- c(0.5, 1.4)
normal_wbc <- c(3.7, 10.4)
normal_hgb <- c(8.5, 10.0) #14-18
normal_plt <- c(133, 450)
normal_sbp <- c(90, 140)
normal_hr <- c(60, 100)

cb_line <- JS(paste0("function (oSettings, json) { $('.spark_scr:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_scr[1], ", normalRangeMax: ", normal_scr[2], " });\n $('.spark_hgb:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_hgb[1], ", normalRangeMax: ", normal_hgb[2], " });\n $('.spark_plt:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_plt[1], ", normalRangeMax: ", normal_plt[2], " });\n $('.spark_wbc:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_wbc[1], ", normalRangeMax: ", normal_wbc[2], " });\n $('.spark_sbp:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_sbp[1], ", normalRangeMax: ", normal_sbp[2], " });\n $('.spark_hr:not(:has(canvas))').sparkline('html', { ", 
    line_string, ", normalRangeMin: ", normal_hr[1], ", normalRangeMax: ", normal_hr[2], " });}"), 
    collapse = "")

d1 <- datatable(df, 
                caption = paste0("CVICU - Updated: ", format(update_time, "%B %d, %Y at %I:%M %p")),
                rownames = FALSE, 
                colnames = c("Patient", "Age", "Sex", "LOS", "SOFA", "Tmax", "SCr", "Hgb", "Plt", "WBC", "SBP", "HR", "UOP", "Alerts"),
                extensions = "FixedHeader",
                options = list(
                    fixedHeader = TRUE,
                    pageLength = 20,
                    order = list(list(0, 'asc')),
                    columnDefs = colDefs1, 
                    fnDrawCallback = cb_line)) %>%
    formatRound("los", 1) %>%
    formatRound("uop_rate", 1)

d1$dependencies <- append(d1$dependencies, htmlwidgets:::getDependency("sparkline"))

d1
```

