---
title: "HVI Patient Dashboard"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = 'U:', output_file = 'hvi_dashboard.html') })
output: flexdashboard::flex_dashboard
---

<style>
    body .main-container {
        max-width: 100%;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(edwr)
library(DT)
library(sparkline)

raw <- list.files("../data/raw", full.names = TRUE) %>%
    sort()

n_files <- length(raw)

update_time <- raw[n_files] %>%
    str_replace_all("hvi_dashboard_|\\.xlsx", "") %>%
    ymd_hms()

data_patients <- read_excel(
    raw[n_files], 
    sheet = "Patients", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "name", 
        "age",
        "gender",
        "los",
        "location"
    )
) 

data_labs <- read_excel(
    raw[n_files], 
    sheet = "Labs",
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "lab.datetime", 
        "lab", 
        "lab.result"
    )
) %>%
    format_dates("lab.datetime", tz = "UTC")

data_meds <- read_excel(
    raw[n_files], 
    sheet = "Meds", 
    skip = 2,
    col_names = c(
        "millennium.id", 
        "event.id", 
        "order.id", 
        "order.parent.id", 
        "med.datetime", 
        "med", 
        "dose", 
        "dose.units", 
        "route", 
        "rate",
        "rate.units",
        "infuse.actions"
    )
) %>%
    format_dates("med.datetime", tz = "UTC")

data_vitals <- read_excel(
    raw[n_files], 
    sheet = "Vitals", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "vital.datetime", 
        "vital", 
        "vital.result", 
        "vital.units"
    )
) %>%
    format_dates("vital.datetime", tz = "UTC")

data_temps <- read_excel(
    raw[n_files], 
    sheet = "Temps", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "vital.datetime", 
        "vital", 
        "vital.result", 
        "vital.units"
    )
) %>%
    format_dates("vital.datetime", tz = "UTC")

data_uop <- read_excel(
    raw[n_files], 
    sheet = "UOP", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "uop.datetime", 
        "uop", 
        "uop.result", 
        "uop.units"
    )
) %>%
    format_dates("uop.datetime", tz = "UTC")

data_measures <- read_excel(
    raw[n_files], 
    sheet = "Measures", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "measure.datetime", 
        "measure", 
        "measure.result", 
        "measure.units"
    )
) %>%
    format_dates("measure.datetime", tz = "UTC")

data_orders <- read_excel(
    raw[n_files], 
    sheet = "Orders", 
    skip = 2, 
    col_names = c(
        "millennium.id", 
        "order.id", 
        "order.start", 
        "order.stop", 
        "frequency", 
        "prn", 
        "order.med", 
        "order.product"
    )
) %>%
    format_dates(c("order.start", "order.stop"), tz = "UTC")
```

```{r}
spark_lines <- function(x, y, nl_min, nl_max, type = "line") {
    spk_chr(
        values = y,
        type = type,
        xvalues = x,
        width = 50,
        lineColor = "black",
        fillColor = FALSE,
        highlightLineColor = "orange",
        highlightSpotColor = "blue",
        normalRangeMin = nl_min[1],
        normalRangeMax = nl_max[1]
    )
}
```

```{r spark}
df_labs <- data_labs %>%
    filter(
        floor_date(lab.datetime, unit = "day") >= ymd(today()) - days(3),
        lab %in% c("Creatinine Lvl", "Hgb", "Platelet", "WBC")
    ) %>%
    mutate_at(
        "lab", 
        str_replace_all, 
        pattern = c("Creatinine Lvl" = "scr")
    ) %>%
    mutate_at("lab", str_to_lower) %>%
    group_by(millennium.id, lab.datetime, lab) %>%
    mutate_at("lab.result", as.numeric) %>%
    summarize_at(
        "lab.result", 
        first, 
        order_by = "lab.datetime"
    ) %>%
    mutate(
        lab.drawn = difftime(
            lab.datetime, 
            update_time, 
            units = "hours"
        )
    ) %>%
    group_by(millennium.id, lab)

spk_labs <- df_labs %>%
    add_count(millennium.id, lab) %>%
    filter(n > 1) %>%
    summarize_at(
        "lab.result", 
        funs(
            spark_lines(
                x = lab.drawn, 
                y = ., 
                nl_min = case_when(
                    lab == "hgb" ~ 8.5,
                    lab == "platelet" ~ 133,
                    lab == "scr" ~ 0.5,
                    lab == "wbc" ~ 3.7
                ),
                nl_max = case_when(
                    lab == "hgb" ~ 10,
                    lab == "platelet" ~ 250,
                    lab == "scr" ~ 1.4,
                    lab == "wbc" ~ 10.4
                )
            )
        )
    ) %>%
    spread(lab, lab.result) %>%
    select(millennium.id, scr, wbc, hgb, platelet)

tmp_bands <- data_labs %>%
    filter(
        lab == "Bands",
        floor_date(lab.datetime, unit = "day")  >= ymd(today()) - days(1)
    ) %>%
    mutate_at("lab", str_to_lower) %>%
    mutate_at("lab.result", as.numeric) %>%
    group_by(millennium.id, lab) %>%
    summarize_at("lab.result", last) 

if (nrow(tmp_bands) == 0) {
    df_bands <- data_patients %>%
        select(millennium.id) %>%
        mutate(bands = NA_integer_)
} else {
    df_bands <- spread(tmp_bands, lab, lab.result)
}
    
df_measures <- data_measures %>%
    mutate_at("measure.result", as.numeric) %>%
    mutate_at("measure", str_to_lower) %>%
    filter(
        (measure == "weight" & measure.units == "kg") | 
            (measure == "height" & measure.units == "cm"),
        !is.na(measure.result)
    ) %>%
    arrange(millennium.id, measure, desc(measure.datetime)) %>%
    distinct(millennium.id, measure, .keep_all = TRUE) %>%
    select(millennium.id, measure, measure.result) %>%
    spread(measure, measure.result)

tmp_pca <- data_measures %>%
    mutate_at("measure.result", as.numeric) %>%
    filter(
        measure %in% c("PCA Doses Delivered", "PCA Total Demands"),
        measure.datetime >= ymd(today()) - days(1)
    ) %>%
    group_by(millennium.id, measure) %>%
    summarize_at("measure.result", sum, na.rm = TRUE) %>%
    mutate_at(
        "measure", 
        str_replace_all, 
        pattern = c(
            "PCA Total Demands" = "demand",
            "PCA Doses Delivered" = "doses"
        )
    ) 

if (nrow(tmp_pca) == 0) {
    df_pca <- data_patients %>%
        select(millennium.id) %>%
        mutate(demand = NA_integer_,
               doses = NA_integer_)
} else {
    df_pca <- spread(tmp_pca, measure, measure.result)

}

hd <- c("Hemodialysis Output Volume", "Hemodialysis Output Vol")
crrt <- c("CRRT Output Vol", "CRRT Actual Pt Fluid Removed Vol")
pd <- c("Peritoneal Dialysis Output Vol", "Peritoneal Dialysis Output Volume")

tmp_uop <- data_uop %>%
    mutate_at("uop.result", as.numeric) %>%
    filter(
        floor_date(uop.datetime, unit = "day")  >= ymd(today()) - days(2),
        !(uop %in% c(hd, crrt, pd))
    ) %>%
    mutate(uop.hr = floor_date(uop.datetime, unit = "hour"),
           uop.date = if_else(
               hour(uop.hr) <= 7, 
               floor_date(uop.hr - days(1), unit = "day"), 
               floor_date(uop.hr, unit = "day")
           )
    ) 

df_uop <- tmp_uop %>%
    group_by(millennium.id, uop.date) %>%
    summarize_at("uop.result", sum, na.rm = TRUE) %>%
    left_join(df_measures, by = "millennium.id") %>%
    mutate(uop.rate = uop.result / weight / 24) %>%
    filter(uop.date == today() - days(1)) %>%
    select(millennium.id, uop.rate)

spk_uop <- tmp_uop %>%
    filter(uop.date == today() - days(1)) %>%
    mutate(uop.drawn = difftime(uop.datetime, update_time, units = "hours")) %>%
    group_by(millennium.id) %>%
    arrange(uop.datetime, .by_group = TRUE) %>%
    add_count(millennium.id) %>%
    filter(n > 1) %>%
    summarize(spk.uop = spark_lines(uop.drawn, uop.result, 50, 150)) 

dialysis <- c("Hemodialysis Output Volume" = "HD", 
              "Hemodialysis Output Vol" = "HD",
              "CRRT Output Vol" = "CRRT",
              "CRRT Actual Pt Fluid Removed Vol" = "CRRT",
              "Peritoneal Dialysis Output Volume" = "PD",
              "Peritoneal Dialysis Output Vol" = "PD")

df_dialysis <- data_uop %>%
    filter(
        floor_date(uop.datetime, unit = "day")  >= ymd(today()) - days(2),
        (uop %in% c(hd, crrt, pd))
    ) %>%
    mutate_at("uop", str_replace_all, pattern = dialysis) %>%
    distinct(millennium.id, uop) %>%
    rename(alert = uop)

df_iabp <- data_measures %>%
    filter(measure == "IABP Mean Pressure",
           measure.datetime >= ymd(today()) - days(1)) %>%
    mutate(alert = "IABP") %>%
    distinct(millennium.id, alert)

df_alert <- data_labs %>%
    filter(
        floor_date(lab.datetime, unit = "day") >= ymd(today()) - days(2),
        lab %in% c("AST", "ALT", "Lactic Acid Lvl", "POC A LA")
    ) %>%
    mutate_at("lab.result", as.numeric) %>%
    mutate_at(
        "lab", 
        str_replace_all, 
        pattern = "Lactic Acid Lvl|POC A LA", 
        replacement = "LA"
    ) %>%
    group_by(millennium.id, lab) %>%
    summarize_at("lab.result", max, na.rm = TRUE) %>%
    filter(
        (lab == "AST" & lab.result >= 300) |
               (lab == "ALT" & lab.result >= 300) |
               (lab == "LA" & lab.result >= 4)
    ) %>%
    rename(alert = lab) %>%
    bind_rows(df_dialysis, df_iabp) %>%
    group_by(millennium.id) %>%
    summarize_at("alert", str_c, collapse = ", ")

df_drips <- data_meds %>%
    filter(
        med.datetime >= ymd(today()) - days(1),
        !is.na(infuse.actions),
        !is.na(rate.units)
    ) %>%
    group_by(millennium.id, med) %>%
    arrange(med.datetime, .by_group = TRUE) %>%
    summarize_at("rate", c("last", "sum")) %>%
    filter(last > 0 | med == "Insulin regular") %>%
    mutate_at("sum", round, digits = 0) %>%
    mutate(
        rate = if_else(med == "Insulin regular", sum, last),
        med_abbrv = str_extract(med, "^.{3}")
    ) %>%
    mutate_at("med_abbrv", str_to_lower) %>%
    unite(drip, med_abbrv, rate, sep = " ") %>%
    group_by(millennium.id) %>%
    summarize_at("drip", str_c, collapse = ", ")

df_ssi <- data_meds %>%
    filter(
        med.datetime >= ymd(today()) - days(2),
        is.na(infuse.actions),
        is.na(rate.units),
        str_detect(med, regex("insulin", ignore_case = TRUE))
    ) %>%
    mutate(
        orig.order.id = order.parent.id,
        ssi.hr = floor_date(med.datetime, unit = "hour"),
        ssi.date = if_else(
            hour(ssi.hr) <= 7, 
            floor_date(ssi.hr - days(1), unit = "day"), 
            floor_date(ssi.hr, unit = "day")
        )
    ) %>%
    filter(ssi.date == today() - days(1)) %>%
    mutate_at("orig.order.id", na_if, 0) %>%
    mutate_at("orig.order.id", funs(coalesce(., order.id))) %>%
    left_join(
        data_orders, 
        by = c("millennium.id", "orig.order.id" = "order.id")
    ) %>%
    filter(prn == "PRN") %>%
    group_by(millennium.id) %>%
    summarize_at("dose", sum, na.rm = TRUE)

vital_names <- c("Arterial Systolic BP 1" = "SBP",
                 "Systolic Blood Pressure" = "SBP",
                 "Respiratory Rate" = "RR",
                 "Glasgow Coma Score" = "GCS",
                 "Apical Heart Rate" = "HR",
                 "POC A PO2" = "PO2",
                 "POC A %FIO2" = "FIO2",
                 "FIO2 \\(%\\)" = "FIO2",
                 "Mean Arterial Pressure (Invasive)" = "MAP",
                 "Mean Arterial Pressure" = "MAP")

df_vitals <- data_vitals %>%
    filter(vital.datetime >= update_time - hours(24)) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    mutate_at("vital", str_to_lower) %>%
    filter(vital %in% c("sbp", "hr")) %>%
    select(-vital.units) %>%
    mutate(
        vital.drawn = difftime(
            vital.datetime, 
            update_time, 
            units = "hours"
        )
    ) %>%
    group_by(millennium.id, vital) %>%
    arrange(vital.datetime, .by_group = TRUE)

spk_vitals <- df_vitals %>%
    add_count(millennium.id, vital) %>%
    filter(n > 1) %>%
    summarize_at(
        "vital.result", 
        funs(
            spark_lines(
                x = vital.drawn, 
                y = ., 
                nl_min = case_when(
                    vital == "sbp" ~ 90,
                    vital == "hr" ~ 60
                ),
                nl_max = case_when(
                    vital == "sbp" ~ 140,
                    vital == "hr" ~ 100
                )
            )
        )
    ) %>%
    spread(vital, vital.result) %>%
    select(millennium.id, sbp, hr)

spk_gluc <- data_labs %>%
    filter(
        floor_date(lab.datetime, unit = "day") >= ymd(today()) - days(2),
        lab == "Glucose POC"
    ) %>%
    mutate(
        lab.drawn = difftime(lab.datetime, update_time, units = "hours"),
        gluc.hr = floor_date(lab.datetime, unit = "hour"),
        gluc.date = if_else(
            hour(gluc.hr) <= 7, 
            floor_date(gluc.hr - days(1), unit = "day"), 
            floor_date(gluc.hr, unit = "day")
        )
    ) %>%
    filter(gluc.date == today() - days(1)) %>%
    group_by(millennium.id) %>%
    arrange(lab.datetime, .by_group = TRUE) %>%
    add_count(millennium.id) %>%
    filter(n > 1) %>%
    summarize(gluc = spark_lines(lab.drawn, lab.result, 80, 180)) 

tmp_temps <- data_temps %>%
    filter(vital.datetime >= update_time - hours(24),
           vital.units == "DegF") %>%
    mutate_at("vital.result", as.numeric) 

df_temps <- tmp_temps %>%
    group_by(millennium.id) %>%
    summarize_at("vital.result", max)

spk_temps <- tmp_temps %>%
    mutate(
        vital.drawn = difftime(
            vital.datetime, 
            update_time, 
            units = "hours"
        )
    ) %>%
    group_by(millennium.id) %>%
    arrange(vital.datetime, .by_group = TRUE) %>%
    add_count(millennium.id) %>%
    filter(n > 1) %>%
    summarize(
        spk.temp = spark_lines(
            vital.drawn, 
            vital.result, 
            97.5, 
            100.5
        )
    ) 

last_scr <- df_labs %>%
    filter(lab == "scr") %>%
    arrange(millennium.id, lab.datetime) %>%
    group_by(millennium.id) %>%
    summarize_at("lab.result", last)

df_crcl <- data_patients %>%
    left_join(last_scr, by = "millennium.id") %>%
    left_join(df_measures, by = "millennium.id") %>%
    group_by(millennium.id) %>%
    mutate(crcl = calc_crcl(age, gender, lab.result, weight, height)) %>%
    select(millennium.id, crcl)

```

```{r sofa}
sofa_vitals <- data_vitals %>%
    filter(
        floor_date(vital.datetime, unit = "day") >= ymd(today()) - hours(24)
    ) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    filter(vital %in% c("MAP", "GCS")) %>%
    group_by(millennium.id, vital) %>%
    summarize_at("vital.result", "min", na.rm = TRUE) %>%
    spread(vital, vital.result) %>%
    mutate_at("GCS", 
              funs(
                  case_when(
                      . < 6 ~ 4,
                      . <= 9 ~ 3,
                      . <= 12 ~ 2,
                      . <= 14 ~ 1,
                      TRUE ~ 0
                  )
              )
    ) %>%
    mutate_at("MAP", 
              funs(
                  case_when(
                      . < 70 ~ 1,
                      TRUE ~ 0
                  )
              )
    )

sofa_vent <- data_measures %>%
    filter(
        floor_date(measure.datetime, unit = "day") >= ymd(today()) - hours(24),
        measure == "Invasive Ventilation Mode"
    ) %>%
    distinct(millennium.id) %>%
    mutate(vent = TRUE)

sofa_resp <- data_vitals %>%
    filter(
        floor_date(vital.datetime, unit = "day") >= ymd(today()) - hours(24)
    ) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    filter(vital %in% c("PO2", "FIO2")) %>%
    select(-vital.units) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    summarize_at(
        "vital.result", 
        funs(
            vital_min = min, 
            vital_max = max
        )
    ) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    mutate(
        vital.result = if_else(
            vital == "PO2", 
            vital_min, 
            vital_max
        )
    ) %>%
    select(-vital_min, -vital_max) %>%
    spread(vital, vital.result) %>%
    group_by(millennium.id) %>%
    arrange(vital.datetime, .by_group = TRUE) %>%
    fill(FIO2) %>%
    mutate(ratio = PO2 / (FIO2 / 100)) %>%
    filter(!is.na(ratio)) %>%
    summarize_at("ratio", "min", na.rm = TRUE) %>%
    left_join(sofa_vent, by = "millennium.id") %>%
    mutate(
        resp_score = case_when(
            ratio < 100 & vent ~ 4,
            ratio < 200 & vent ~ 3,
            ratio < 300 ~ 2,
            ratio < 400 ~ 1,
            TRUE ~ 0
        )
    ) %>%
    select(millennium.id, resp_score)

labs <- c("Creatinine Lvl" = "scr",
          "Platelet" = "plt", 
          "Bili Total" = "bili")

sofa_labs <- data_labs %>%
    filter(
        floor_date(lab.datetime, unit = "day") >= ymd(today()) - hours(24),
        lab %in% c("Creatinine Lvl", "Platelet", "Bili Total")
    ) %>%
    mutate_at("lab", str_replace_all, pattern = labs) %>%
    mutate_at("lab.result", as.numeric) %>%
    arrange(millennium.id, lab, lab.datetime) %>%
    distinct(millennium.id, lab, lab.datetime, .keep_all = TRUE) %>%
    group_by(millennium.id, lab.datetime) %>%
    spread(lab, lab.result) %>%
    group_by(millennium.id) %>%
    summarize_at(
        c("scr", "plt", "bili"), 
        funs(min, max), 
        na.rm = TRUE
    ) %>%
    select(millennium.id, scr_max, plt_min, bili_max) %>%
    mutate_at(
        "scr_max", 
        funs(
            case_when(
                . >= 5 ~ 4,
                . >= 3.5 ~ 3,
                . >= 2 ~ 2,
                . >= 1.2 ~ 1,
                TRUE ~ 0
            )
        )
    ) %>%
    mutate_at(
        "plt_min", 
        funs(
            case_when(
                . < 20 ~ 4,
                . < 50 ~ 3,
                . < 100 ~ 2,
                . < 150 ~ 1,
                TRUE ~ 0
            )
        )
    ) %>%
    mutate_at(
        "bili_max", 
        funs(
            case_when(
                . >= 12 ~ 4,
                . >= 6 ~ 3,
                . >= 2 ~ 2,
                . >= 1.2 ~ 1,
                TRUE ~ 0
            )
        )
    )
    
sofa_uop <- data_uop %>%
    mutate_at("uop.result", as.numeric) %>%
    filter(
        floor_date(uop.datetime, unit = "day") >= ymd(today()) - days(2),
        !(uop %in% c(hd, crrt, pd))
    ) %>%
    mutate(
        uop_hr = floor_date(uop.datetime, unit = "hour"),
        uop_date = if_else(
            hour(uop_hr) <= 7, 
            floor_date(uop_hr - days(1), unit = "day"), 
            floor_date(uop_hr, unit = "day")
        )
    ) %>%
    group_by(millennium.id, uop_date) %>%
    summarize_at("uop.result", sum, na.rm = TRUE) %>%
    filter(uop_date == ymd(today() - days(1))) %>%
    mutate_at(
        "uop.result", 
        funs(
            case_when(
                . < 200 ~ 4,
                . < 500 ~ 3,
                TRUE ~ 0
            )
        )
    ) %>%
    select(millennium.id, uop.result)

sofa_meds <- data_meds %>%
    mutate_at("med", str_to_lower) %>%
    filter(
        floor_date(med.datetime, unit = "day") >= ymd(today()) - hours(24),
        med %in% c(
            "dopamine", 
            "dobutamine", 
            "epinephrine", 
            "norepinephrine"
        ),
        !is.na(rate.units),
        rate > 0
    ) %>%
    left_join(df_measures, by = "millennium.id") %>%
    mutate(
        rate_kg = if_else(
            rate.units == "microgram/min", 
            rate / weight, 
            rate
        )
    ) %>%
    group_by(millennium.id, med) %>%
    summarize_at("rate_kg", funs(rate_max = max), na.rm = TRUE) %>%
    mutate_at(
        "med", 
        factor, 
        levels = c(
            "dopamine",
            "dobutamine",
            "epinephrine",
            "norepinephrine"
        )
    ) %>%
    spread(med, rate_max, drop = FALSE, fill = 0) %>%
    mutate_at(
        "dopamine", 
        funs(
            case_when(
                . > 15 ~ 4,
                . > 5 ~ 3,
                . > 0 ~ 2,
                TRUE ~ 0
            )
        )
    ) %>%
    mutate_at(
        "dobutamine", 
        funs(
            case_when(
                . > 0 ~ 2,
                TRUE ~ 0
            )
        )
    ) %>%
    mutate_at(
        c("epinephrine", "norepinephrine"), 
        funs(
            case_when(
                . > 0.1 ~ 4,
                . > 0 ~ 3,
                TRUE ~ 0
            )
        )
    )

df_sofa <- data_patients %>%
    select(millennium.id) %>%
    left_join(sofa_resp, by = "millennium.id") %>%
    left_join(sofa_labs, by = "millennium.id") %>%
    left_join(sofa_vitals, by = "millennium.id") %>%
    left_join(sofa_uop, by = "millennium.id") %>%
    left_join(sofa_meds, by = "millennium.id") %>%
    mutate_all(funs(coalesce(., 0))) %>%
    group_by(millennium.id) %>%
    mutate(
        bp_score = max(
            MAP, dopamine, dobutamine, epinephrine, norepinephrine, 
            na.rm = TRUE
        ),
        renal_score = max(scr_max, uop.result, na.rm = TRUE),
        sofa = sum(
            resp_score, 
            plt_min, 
            GCS, 
            bili_max, 
            bp_score, 
            renal_score, 
            na.rm = TRUE
        )
    ) %>%
    select(millennium.id, sofa)

df_qsofa <- data_vitals %>%
    filter(
        floor_date(vital.datetime, unit = "day") >= ymd(today()) - days(1)
    ) %>%
    mutate_at("vital.result", as.numeric) %>%
    mutate_at("vital", str_replace_all, pattern = vital_names) %>%
    select(-vital.units) %>%
    group_by(millennium.id, vital.datetime, vital) %>%
    summarize_at("vital.result", min) %>%
    spread(vital, vital.result) %>%
    select(-HR) %>%
    group_by(millennium.id) %>%
    fill(GCS) %>%
    group_by(millennium.id) %>%
    summarize_at(
        c("SBP", "RR", "GCS"), 
        c("min", "max"), 
        na.rm = TRUE
    ) %>%
    group_by(millennium.id) %>%
    mutate(
        qsofa = sum(
            SBP_min <= 100, 
            RR_max >= 22, 
            GCS_min < 15, 
            na.rm = TRUE
        )
    ) %>%
    select(millennium.id, qsofa)
```

```{r}
df <- data_patients %>%
    mutate_at("gender", str_extract, pattern = "^M|^F") %>%
    left_join(df_sofa, by = "millennium.id") %>%
    left_join(spk_temps, by = "millennium.id") %>%
    left_join(df_temps, by = "millennium.id") %>%
    left_join(spk_labs, by = "millennium.id") %>%
    left_join(df_crcl, by = "millennium.id") %>%
    left_join(df_bands, by = "millennium.id") %>%
    left_join(spk_vitals, by = "millennium.id") %>%
    left_join(spk_gluc, by = "millennium.id") %>%
    left_join(df_ssi, by = "millennium.id") %>%
    left_join(spk_uop, by = "millennium.id") %>%
    left_join(df_uop, by = "millennium.id") %>%
    left_join(df_drips, by = "millennium.id") %>%
    left_join(df_alert, by = "millennium.id") %>%
    left_join(df_pca, by = "millennium.id") %>%
    select(name:scr, crcl, wbc, bands, hgb:doses)
```

```{r}
col_names <- c(
    "Patient", 
    "Age",
    "Sex",
    "LOS",
    "SOFA",
    "Temp",
    "Tmax",
    "SCr",
    "CrCl",
    "WBC", 
    "B%",
    "Hgb",
    "Plt",
    "SBP",
    "HR", 
    "Gluc",
    "SSI", 
    "UOP", 
    "Avg", 
    "Drips",
    "Alerts",
    "PCA",
    "Doses"
)

make_table <- function(x) {
    x %>%
        select(-location) %>%
        datatable(
            caption = paste0(
                "Updated: ", 
                format(update_time, "%B %d, %Y at %I:%M %p")
            ),
            rownames = FALSE, 
            escape = FALSE,
            colnames = col_names,
            extensions = "FixedHeader",
            options = list(
                dom = "t",
                fixedHeader = TRUE,
                pageLength = 21,
                order = list(list(0, 'asc')),
                initComplete = JS(
                    "function(settings, json) {",
                    "$(this.api().table().header()).css({'font-size': '80%'});",
                    "}"
                ),
                fnDrawCallback = JS(
                    "function(){ HTMLWidgets.staticRender(); }"
                )
            )
        ) %>%
        formatRound(c("los", "vital.result", "uop.rate"), 1) %>%
        formatRound("crcl", 0) %>%
        formatStyle(columns = c(1:ncol(x)), fontSize = "80%") %>%
        spk_add_deps()
}
```


Column {.tabset}
-----------------------------------------------------------------------

### CVICU

```{r}
df %>%
    filter(location == "HH CVICU") %>%
    make_table()
```

### CCU

```{r}
df %>%
    filter(location == "HH CCU") %>%
    make_table()
```
