WITH CURR_PTS AS (
	SELECT DISTINCT
		ENCNTR_DOMAIN.ENCNTR_ID,
		ENCNTR_DOMAIN.PERSON_ID,
		ENCNTR_ALIAS.ALIAS,
		ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD,
		ENCNTR_DOMAIN.LOC_BED_CD,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM,
		PERSON.NAME_FULL_FORMATTED AS PT_NAME,
		PERSON.BIRTH_DT_TM,
		TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) - PERSON.BIRTH_DT_TM) / 365.25, 0) AS AGE,
		PERSON.SEX_CD,
		CASE PERSON.SEX_CD
			WHEN 272 THEN 0.85
			ELSE 1
		END AS CRCL_GENDER_MOD,
		PRSNL.NAME_FULL_FORMATTED AS MD_NAME
	FROM
		ENCNTR_ALIAS,
		ENCNTR_DOMAIN,
		ENCNTR_PRSNL_RELTN,
		ENCOUNTER,
		PERSON,
		PRSNL
	WHERE
		ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = 5541 -- HH CVICU
		AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619 -- FIN NBR
		AND ENCNTR_DOMAIN.PERSON_ID = PERSON.PERSON_ID
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.EXPIRATION_IND = 0
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029 -- Physician Attending
		AND ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL.PERSON_ID
), BLOOD_PRESSURE AS (
	SELECT DISTINCT
		pi_get_cv_display(CURR_PTS.LOC_BED_CD) AS BED,
		CLINICAL_EVENT.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS EVENT_END_DT_TM,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		/*
		CASE pi_get_cv_display(CLINICAL_EVENT.EVENT_CD)
			WHEN 'Systolic Blood Pressure' THEN 'Systolic'
			WHEN 'Arterial Systolic BP 1' THEN 'Systolic'
			WHEN 'Mean Arterial Pressure' THEN 'Mean Arterial'
			WHEN 'Mean Arterial Pressure (Invasive)' THEN 'Mean Arterial'
			WHEN 'Diastolic Blood Pressure' THEN 'Diastolic'
			WHEN 'Arterial Diastolic BP 1' THEN 'Diastolic'
		END AS EVENT,
		*/
		TO_NUMBER(REGEXP_REPLACE(CLINICAL_EVENT.RESULT_VAL, '>|<')) AS RESULT_VAL
	FROM
		CLINICAL_EVENT,
		CURR_PTS
	WHERE
		CURR_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 159 -- NUM
		AND CURR_PTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD IN (
			30098, -- Systolic Blood Pressure
			134401648, -- Arterial Systolic BP 1
			30051, -- Diastolic Blood Pressure
			134401703, -- Arterial Diastolic BP 1
			119822453, -- Mean Arterial Pressure
			173814326 -- Mean Arterial Pressure (Invasive)
		)
		AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 1, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
/*
), BP_PIVOT AS (
	SELECT * FROM BLOOD_PRESSURE
	PIVOT(
		MIN(RESULT_VAL) FOR EVENT IN (
			'Systolic Blood Pressure' AS SBP,
			'Arterial Systolic BP 1' AS SBP_ART,
			'Mean Arterial Pressure' AS MAP,
			'Mean Arterial Pressure (Invasive)' AS MAP_ART,
			'Diastolic Blood Pressure' AS DBP,
			'Arterial Diastolic BP 1' AS DBP_ART
		)
	)
*/
)

SELECT * FROM BLOOD_PRESSURE
