SELECT DISTINCT
    ENCNTR_DOMAIN.ENCNTR_ID AS ENCOUNTER_ID,
	CE_INTAKE_OUTPUT_RESULT.EVENT_ID AS EVENT_ID,
	TO_CHAR(pi_from_gmt(CE_INTAKE_OUTPUT_RESULT.IO_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS IO_DATETIME,
	CV_REFERENCE_EVENT.DISPLAY AS EVENT,
	CE_INTAKE_OUTPUT_RESULT.IO_VOLUME AS VOLUME,
	CASE CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG
		WHEN 1 THEN 'In'
		ELSE 'Out'
	END AS IO_TYPE
FROM
    CE_INTAKE_OUTPUT_RESULT,
    CODE_VALUE CV_REFERENCE_EVENT,
    ENCNTR_DOMAIN
WHERE
    ENCNTR_DOMAIN.ACTIVE_IND = 1
    AND ENCNTR_DOMAIN.LOC_FACILITY_CD = 3310
    AND ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = 5541
    AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
    AND (
        ENCNTR_DOMAIN.ENCNTR_ID = CE_INTAKE_OUTPUT_RESULT.ENCNTR_ID
        AND CE_INTAKE_OUTPUT_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
        AND CE_INTAKE_OUTPUT_RESULT.REFERENCE_EVENT_CD = CV_REFERENCE_EVENT.CODE_VALUE
        AND CE_INTAKE_OUTPUT_RESULT.IO_END_DT_TM >= pi_to_gmt(SYSDATE - 1, pi_time_zone(2, @Variable('BOUSER')))
    )
