SELECT DISTINCT
    ENCNTR_DOMAIN.ENCNTR_ID AS ENCOUNTER_ID,
	ENCNTR_ALIAS.ALIAS AS FIN,
    CV_NURSE_UNIT.DISPLAY AS NURSE_UNIT,
    CV_BED.DISPLAY AS BED,
    SYSDATE - ENCOUNTER.REG_DT_TM AS LOS,
    PERSON.NAME_FULL_FORMATTED AS NAME,
    TRUNC(((pi_from_gmt(ENCOUNTER.REG_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) - PERSON.BIRTH_DT_TM) / 365.25, 0) AS AGE,
    CV_SEX.DISPLAY AS SEX,
    PRSNL_MD.NAME_FULL_FORMATTED AS ATTENDING
FROM
    CODE_VALUE CV_BED,
    CODE_VALUE CV_NURSE_UNIT,
	CODE_VALUE CV_SEX,
	ENCNTR_ALIAS,
    ENCNTR_DOMAIN,
	ENCNTR_PRSNL_RELTN,
    ENCOUNTER,
    PERSON,
    PRSNL PRSNL_MD
WHERE
    ENCNTR_DOMAIN.ACTIVE_IND = 1
    AND ENCNTR_DOMAIN.LOC_FACILITY_CD = 3310
    AND ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = 5541
    AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
    AND ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = CV_NURSE_UNIT.CODE_VALUE
    AND ENCNTR_DOMAIN.LOC_BED_CD = CV_BED.CODE_VALUE
    AND (
        ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
    )
	AND (
		ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_ALIAS.ENCNTR_ID
		AND ENCNTR_ALIAS.ACTIVE_IND = 1
		AND ENCNTR_ALIAS.END_EFFECTIVE_DT_TM > SYSDATE
		AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
	)
    AND (
        ENCNTR_DOMAIN.PERSON_ID = PERSON.PERSON_ID
        AND PERSON.ACTIVE_IND = 1
        AND PERSON.SEX_CD = CV_SEX.CODE_VALUE
    )
	AND (
		ENCNTR_DOMAIN.ENCNTR_ID = ENCNTR_PRSNL_RELTN.ENCNTR_ID
		AND ENCNTR_PRSNL_RELTN.ACTIVE_IND = 1
		AND ENCNTR_PRSNL_RELTN.ENCNTR_PRSNL_R_CD = 368029
		AND ENCNTR_PRSNL_RELTN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_PRSNL_RELTN.PRSNL_PERSON_ID = PRSNL_MD.PERSON_ID
	)

