SELECT DISTINCT
    ENCNTR_DOMAIN.ENCNTR_ID AS ENCOUNTER_ID,
	CLINICAL_EVENT.EVENT_ID AS EVENT_ID,
	TO_CHAR(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))), 'YYYY-MM-DD"T"HH24:MI:SS') AS EVENT_DATETIME,
	CV_EVENT.DISPLAY AS EVENT,
	CLINICAL_EVENT.RESULT_VAL AS RESULT,
	CV_RESULT_UNITS.DISPLAY AS RESULT_UNIT
FROM
    CLINICAL_EVENT,
    CODE_VALUE CV_EVENT,
    CODE_VALUE CV_RESULT_UNITS,
    ENCNTR_DOMAIN
WHERE
    ENCNTR_DOMAIN.ACTIVE_IND = 1
    AND ENCNTR_DOMAIN.LOC_FACILITY_CD = 3310
    AND ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = 5541
    AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
    AND (
        ENCNTR_DOMAIN.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
        AND CLINICAL_EVENT.EVENT_CD IN (31090, 34402, 30349, 30514, 30544, 31854, 33044, 33552, 32197, 240922314)
        AND CLINICAL_EVENT.EVENT_CD = CV_EVENT.CODE_VALUE
        AND CLINICAL_EVENT.RESULT_UNITS_CD = CV_RESULT_UNITS.CODE_VALUE
        AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 3, pi_time_zone(2, @Variable('BOUSER')))
    )
