WITH CURR_PTS AS (
	SELECT DISTINCT
		ENCNTR_DOMAIN.ENCNTR_ID,
		ENCNTR_DOMAIN.PERSON_ID,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM
	FROM
		ENCNTR_DOMAIN,
		ENCOUNTER
	WHERE
		ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD IN (
			4137, -- HH CCU
			5541 -- HH CVICU 
		) 
		AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), DRIPS AS (
	SELECT DISTINCT
		CURR_PTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.PARENT_EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		CE_MED_RESULT.IV_EVENT_CD
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		CURR_PTS
	WHERE
		CURR_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND CURR_PTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 1, pi_time_zone(2, @Variable('BOUSER'))) -- make from 0700 the previous day
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
), LAST_CHARTED AS (
	SELECT
		DRIPS.ENCNTR_ID,
		LOWER(pi_get_cv_display(DRIPS.EVENT_CD)) AS MEDICATION,
		MAX(DRIPS.INFUSION_RATE) KEEP (DENSE_RANK LAST ORDER BY DRIPS.EVENT_END_DT_TM) AS RATE
	FROM
		DRIPS
	WHERE
		DRIPS.EVENT_CD NOT IN (
			34239833, -- Administration Information
			37557260 -- Insulin regular	
		)
		AND DRIPS.IV_EVENT_CD IN (
			688706, -- Begin Bag
			688709 -- Rate Change
		)
	GROUP BY
		DRIPS.ENCNTR_ID,
		DRIPS.EVENT_CD
), CURRENT_RATES AS (
	SELECT *
	FROM LAST_CHARTED
	WHERE RATE > 0
), INSULIN_DRIPS AS (
	SELECT
		DRIPS.ENCNTR_ID,
		DRIPS.PARENT_EVENT_ID,
		DRIPS.EVENT_CD
	FROM
		DRIPS
	WHERE
		DRIPS.EVENT_CD = 37557260 -- Insulin regular	
), INSULIN_IO AS (
	SELECT
		INSULIN_DRIPS.ENCNTR_ID,
		INSULIN_DRIPS.EVENT_CD,
		CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG,
		CE_INTAKE_OUTPUT_RESULT.IO_VOLUME		
	FROM
		CE_INTAKE_OUTPUT_RESULT,
		INSULIN_DRIPS
	WHERE
		INSULIN_DRIPS.PARENT_EVENT_ID = CE_INTAKE_OUTPUT_RESULT.EVENT_ID
), INSULIN_VOL AS (
	SELECT
		INSULIN_IO.ENCNTR_ID,
		LOWER(pi_get_cv_display(INSULIN_IO.EVENT_CD)) AS MEDICATION,
		ROUND(SUM(INSULIN_IO.IO_VOLUME), 0) AS RATE
	FROM
		INSULIN_IO
	GROUP BY
		INSULIN_IO.ENCNTR_ID,
		INSULIN_IO.EVENT_CD
)

SELECT * FROM CURRENT_RATES

UNION

SELECT * FROM INSULIN_VOL
