WITH CURR_PTS AS (
	SELECT DISTINCT
		ENCNTR_DOMAIN.ENCNTR_ID,
		ENCNTR_DOMAIN.PERSON_ID,
		ENCOUNTER.ARRIVE_DT_TM,
		ENCOUNTER.REG_DT_TM
	FROM
		ENCNTR_DOMAIN,
		ENCOUNTER
	WHERE
		ENCNTR_DOMAIN.LOC_NURSE_UNIT_CD = 5541 -- HH CVICU
		AND ENCNTR_DOMAIN.END_EFFECTIVE_DT_TM > DATE '2099-12-31'
		AND ENCNTR_DOMAIN.ENCNTR_ID = ENCOUNTER.ENCNTR_ID
), INS_OUTS AS (
	SELECT DISTINCT
		CURR_PTS.ENCNTR_ID,
		pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS EVENT_DATETIME,
		CLINICAL_EVENT.EVENT_ID,
		pi_get_cv_display(CLINICAL_EVENT.EVENT_CD) AS EVENT,
		CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG,
		CE_INTAKE_OUTPUT_RESULT.IO_VOLUME
	FROM
		CE_INTAKE_OUTPUT_RESULT,
		CLINICAL_EVENT,
		CURR_PTS
	WHERE
		CURR_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD IN (
			158, -- MED
			159 -- NUM
		)
		/*
		AND CLINICAL_EVENT.EVENT_CD(+) IN (
			17664566, -- Urine Voided
			699895758, -- Urine Voided Volume
			134426203, -- Urine Output Initial (mL)
			700105361, -- Indwelling Cath Output Volume:
			700105503, -- Indwelling Cath Urine Output Initial:
			700168898 -- Intermittent Catheter Output Volume
		)
		*/
		AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 1, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.EVENT_ID = CE_INTAKE_OUTPUT_RESULT.EVENT_ID
		AND CE_INTAKE_OUTPUT_RESULT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
), INSULIN_DRIPS AS (
	SELECT DISTINCT
		CURR_PTS.ENCNTR_ID,
		CLINICAL_EVENT.EVENT_END_DT_TM,
		CLINICAL_EVENT.EVENT_ID,
		CLINICAL_EVENT.PARENT_EVENT_ID,
		CLINICAL_EVENT.EVENT_CD,
		CE_MED_RESULT.ADMIN_DOSAGE,
		CE_MED_RESULT.INFUSION_RATE,
		CE_MED_RESULT.INFUSION_UNIT_CD,
		CE_MED_RESULT.IV_EVENT_CD,
		CE_MED_RESULT.INFUSED_VOLUME,
		CE_MED_RESULT.INFUSED_VOLUME_UNIT_CD
	FROM
		CE_MED_RESULT,
		CLINICAL_EVENT,
		CURR_PTS
	WHERE
		CURR_PTS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.EVENT_CLASS_CD = 158 -- MED
		AND CURR_PTS.PERSON_ID = CLINICAL_EVENT.PERSON_ID
		AND CLINICAL_EVENT.EVENT_CD = 37557260 -- Insulin regular
		AND CLINICAL_EVENT.EVENT_END_DT_TM >= pi_to_gmt(SYSDATE - 2, pi_time_zone(2, @Variable('BOUSER')))
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.IV_EVENT_CD > 0
), INSULIN_IO AS (
	SELECT
		INSULIN_DRIPS.ENCNTR_ID,
		pi_from_gmt(INSULIN_DRIPS.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER')))) AS EVENT_DATETIME,
		INSULIN_DRIPS.EVENT_ID,
		INSULIN_DRIPS.PARENT_EVENT_ID,
		pi_get_cv_display(INSULIN_DRIPS.EVENT_CD) AS EVENT,
		CE_INTAKE_OUTPUT_RESULT.IO_TYPE_FLAG,
		CE_INTAKE_OUTPUT_RESULT.IO_VOLUME		
	FROM
		CE_INTAKE_OUTPUT_RESULT,
		INSULIN_DRIPS
	WHERE
		INSULIN_DRIPS.PARENT_EVENT_ID = CE_INTAKE_OUTPUT_RESULT.EVENT_ID
		
)

/*
SELECT
	DRIPS.*,
	pi_get_cv_display(EVENT_CD) AS EVENT,
	pi_get_cv_display(INFUSION_UNIT_CD) AS INFUSION_UNIT,
	pi_get_cv_display(IV_EVENT_CD) AS IV_EVENT,
	pi_get_cv_display(INFUSED_VOLUME_UNIT_CD) AS INFUSED_VOLUME_UNIT
FROM DRIPS
*/

SELECT * FROM INSULIN_IO